# tasks file for profile-n01580903
---
- name: Append lines to /etc/profile
  ansible.builtin.blockinfile:
    path: /etc/profile
    block: |
      "#Test block added by Ansible......n01580903""
      export TMOUT=1500
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    insertafter: EOF