---
- name: Create 4GB partition
  community.general.parted:
    device: /dev/sdc
    number: 1
    state: present
    part_start: 0%
    part_end: 4GiB

- name: Create 5GB partition
  community.general.parted:
    device: /dev/sdc
    number: 2
    state: present
    part_start: 4GiB
    part_end: 9GiB

- name: Format /dev/sdc1 with XFS
  ansible.builtin.filesystem:
    fstype: xfs
    dev: /dev/sdc1

- name: Format /dev/sdc2 with EXT4
  ansible.builtin.filesystem:
    fstype: ext4
    dev: /dev/sdc2

- name: Mount /dev/sdc1 on /part1
  ansible.posix.mount:
    path: /part1
    src: /dev/sdc1
    fstype: xfs
    state: mounted

- name: Mount /dev/sdc2 on /part2
  ansible.posix.mount:
    path: /part2
    src: /dev/sdc2
    fstype: ext4
    state: mounted