---
galaxy_info:
  author: Your Name
  description: Role to update /etc/profile
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: CentOS
      versions:
        - 8
  galaxy_tags:
    - system
    - profile

dependencies: []